### ISSUE TITLE
clojurescript included by default

### ISSUE THREAD

**Issue by Ramblurr** [whamtet/simpleui#33]
I'm not sure how other projects in the clj/cljs ecosystem handle this, but because simpleui depends on hiccups, that means the big fat cljs dependency is included in my uberjar.

I tried adding 
`:exclusions [macchiato/hiccups]` to my `simpleui/simpleui` in deps.edn, but then I get:

```
Compiling Clojure...
Execution error (FileNotFoundException) at simpleui.core/loading (core.clj:1).
Could not locate cljs/env__init.class, cljs/env.clj or cljs/env.cljc on classpath.
```

Is it possible to make the cljs dependency optional? I'm trying to slim down my uberjar because I'm deploying on a raspberry pi which can be sensitive to big fat jars.

**Comment by whamtet** [comment]
Thanks for pointing this out @Ramblurr .  In general we don't want to include cljs because that's the entire point of having SimpleUI.  The main exception is the https://simpleui.io tutorial which uses Cloudflare workers to evaluate untrusted code.  I'll disable the hiccups reference for now.  Can you use a git reference in your deps.edn?

```clojure
simpleui/simpleui {:git/url "https://github.com/whamtet/simpleui",
                    :git/sha "0fe033e6cfd7acce31b56293c22bd7c46beaba3c"}
```

**Comment by Ramblurr** [comment]
> In general we don't want to include cljs because that's the entire point of having SimpleUI.

exactly my thoughts :)



> Can you use a git reference in your deps.edn?

perfect thanks!
